replicaCount: 1

image:
  repository: "ewr.vultrcr.com/wellpay/wellpay-frontend"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: "vcr-creds"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: wellfx.store
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wellfx-store-tls
      hosts:
        - wellfx.store

certManager:
  enabled: true
  issuerName: wellpay-letsencrypt
  email: ""
  server: "https://acme-v02.api.letsencrypt.org/directory"
  privateKeySecretName: wellpay-letsencrypt-account-key
  ingressClass: nginx

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
