services:
  frontend:
    image: wellpay-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wellpay-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
